# Generated by Django 6.0.7 on 2026-08-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Taslak', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetheader')),
            ],
        ),
        migrations.AddField(
            model_name='budgetheader',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.department'),
        ),
        migrations.AddField(
            model_name='budgetheader',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.period'),
        ),
    ]
