# Generated by Django 6.0.7 on 2026-08-02 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('budget_type', models.CharField(choices=[('uretim', 'Üretim Finansı'), ('satis', 'Satış Finansı'), ('maliyet', 'Maliyet Finansı'), ('nakit', 'Nakit Akışı')], max_length=20, verbose_name='Bütçe Türü')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.AlterModelOptions(
            name='budgetheader',
            options={'verbose_name': 'Bütçe', 'verbose_name_plural': 'Bütçeler'},
        ),
        migrations.AlterModelOptions(
            name='budgetline',
            options={'verbose_name': 'Bütçe Kalemi', 'verbose_name_plural': 'Bütçe Kalemleri'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departman', 'verbose_name_plural': 'Departmanlar'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Dönem', 'verbose_name_plural': 'Dönemler'},
        ),
        migrations.AddField(
            model_name='budgetheader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetheader',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='budgetheader',
            name='version_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Versiyon No'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ay'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Departman Yöneticisi'),
        ),
        migrations.AddField(
            model_name='period',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Kilitli mi'),
        ),
        migrations.AlterField(
            model_name='budgetheader',
            name='budget_type',
            field=models.CharField(choices=[('uretim', 'Üretim Finansı'), ('satis', 'Satış Finansı'), ('maliyet', 'Maliyet Finansı'), ('nakit', 'Nakit Akışı')], max_length=20, verbose_name='Bütçe Türü'),
        ),
        migrations.AlterField(
            model_name='budgetheader',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.department', verbose_name='Departman'),
        ),
        migrations.AlterField(
            model_name='budgetheader',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.period', verbose_name='Dönem'),
        ),
        migrations.AlterField(
            model_name='budgetheader',
            name='status',
            field=models.CharField(choices=[('taslak', 'Taslak'), ('dept_onay', 'Departman Onayında'), ('finans_onay', 'Finans İncelemesinde'), ('ust_onay', 'Üst Yönetim Onayında'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='taslak', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='budget_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgets.budgetheader', verbose_name='Bütçe'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Planlanan Tutar'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Departman Adı'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Dönem Adı'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(verbose_name='Başlangıç Tarihi'),
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField(verbose_name='Sıra')),
                ('status', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('revizyon', 'Revizyon İstendi')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('comment', models.TextField(blank=True, verbose_name='Yorum')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='İşlem Tarihi')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Onaylayacak Kişi')),
                ('budget_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='budgets.budgetheader', verbose_name='Bütçe')),
            ],
            options={
                'verbose_name': 'Onay Adımı',
                'verbose_name_plural': 'Onay Adımları',
            },
        ),
        migrations.CreateModel(
            name='ActualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Ay')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gerçekleşen Tutar')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='İçe Aktarım Tarihi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.department', verbose_name='Departman')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.period', verbose_name='Dönem')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Gerçekleşen Veri',
                'verbose_name_plural': 'Gerçekleşen Veriler',
            },
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budgets.category', verbose_name='Kategori'),
        ),
    ]
