# Generated by Django 6.0.7 on 2026-08-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_category_alter_budgetheader_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetheader',
            name='budget_type',
            field=models.CharField(choices=[('uretim', 'Üretim Bütçesi'), ('satis', 'Satış Bütçesi'), ('maliyet', 'Maliyet Bütçesi'), ('nakit', 'Nakit Akışı Bütçesi'), ('personel', 'Personel / İK Bütçesi'), ('yatirim', 'Yatırım (CAPEX) Bütçesi'), ('pazarlama', 'Pazarlama Bütçesi'), ('genel_yonetim', 'Genel Yönetim Gideri Bütçesi'), ('arge', 'Ar-Ge Bütçesi'), ('bakim_onarim', 'Bakım-Onarım Bütçesi')], max_length=20, verbose_name='Bütçe Türü'),
        ),
        migrations.AlterField(
            model_name='category',
            name='budget_type',
            field=models.CharField(choices=[('uretim', 'Üretim Bütçesi'), ('satis', 'Satış Bütçesi'), ('maliyet', 'Maliyet Bütçesi'), ('nakit', 'Nakit Akışı Bütçesi'), ('personel', 'Personel / İK Bütçesi'), ('yatirim', 'Yatırım (CAPEX) Bütçesi'), ('pazarlama', 'Pazarlama Bütçesi'), ('genel_yonetim', 'Genel Yönetim Gideri Bütçesi'), ('arge', 'Ar-Ge Bütçesi'), ('bakim_onarim', 'Bakım-Onarım Bütçesi')], max_length=20, verbose_name='Bütçe Türü'),
        ),
    ]
