# Generated by Django 6.0.7 on 2026-08-07 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='budget_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.budgetheader', verbose_name='İlgili Bütçe'),
        ),
    ]
