# Generated by Django 6.0.7 on 2026-08-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_notification_budget_header'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('olusturuldu', 'Oluşturuldu'), ('guncellendi', 'Güncellendi'), ('silindi', 'Silindi'), ('onaya_gonderildi', 'Onaya Gönderildi'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('versiyon_olusturuldu', 'Yeni Versiyon Oluşturuldu')], max_length=30, verbose_name='İşlem')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Denetim Kaydı',
                'verbose_name_plural': 'Denetim Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
